### ISSUE TITLE
Ubuntu hostnames not updating.

### ISSUE THREAD

**Issue by CHernandezNY** [CHernandezNY/k3s-ansible#1]
## Expected Behavior

after running the deploy for an ubuntu cluster the hostnames are not updated.

## Current Behavior

ansible playbook should use the mac address to hostname mapping in the all.yml file to set the host name for each node in the cluster.
## Steps to Reproduce

1. Run playbook on Unbuntu cluster

## Context (variables)

Operating system:

Ubuntu v20.04

Hardware:

### Variables Used:

`all.yml`

```yml
# Mapping of hardware MAC addresses should be configured with specific IPs and Hostnames
mac_address_mapping:
  "00:01:ff:33:d6:11":
    name: ctrl-01.example.local
    ip: IP.ADDRESS.ONE
  "00:01:ff:1a:e7:72":
    name: ctrl-02.example.local
    ip: IP.ADDRESS.TWO
  "00:01:ff:e0:9b:33":
    name: ctrl-03.example.local
    ip: IP.ADDRESS.THREE
  "00:01:ff:ca:72:34":
    name: wrkr-01.example.local
    ip: IP.ADDRESS.FOUR
  "00:01:ff:86:5c:c5":
    name: wrkr-02.example.local
    ip: IP.ADDRESS.FIVE
  "00:01:ff:58:51:c6":
    name: wrkr-03.example.local
    ip: IP.ADDRESS.SIX
  "00:01:ff:78:78:d7":
    name: nginx-lb.example.local
    ip: IP.ADDRESS.SEVEN
```

### Hosts 

`host.ini`

```ini
[controller]
IP.ADDRESS.ONE
IP.ADDRESS.TWO
IP.ADDRESS.THREE

[worker]
IP.ADDRESS.FOUR
IP.ADDRESS.FIVE

[balancer]
IP.ADDRESS.SEVEN

[k3s_cluster:children]
controller
worker
```
